version: 0.1
phases:    
    install:        
        commands:            
            - 'touch .npmignore'            
            - 'yarn global add gatsby'    
    pre_build:        
        commands:            
            - 'yarn'    
    build:        
        commands:            
            - 'gatsby build'    
    post_build:        
        commands:            
            - 'aws s3 sync "public/" "s3://blake.art" --delete --acl "public-read"'
artifacts:    
    base-directory: public    
    files:        
        - '**/*'    
    discard-paths: yes
